### PR TITLE
Resolve conflict in nertwork/ansible-frr

### PR DESCRIPTION
**Pull request by elcomtik**
I can't resolve issues in nertwork PR https://github.com/mrlesmithjr/ansible-frr/pull/36 , so I created mine, where I resolve them

### CODE REVIEW

**Comment by elcomtik** [comment]
Test failed on on Python 2.7 and lint errors 403. I would prefer to remove testing by unsupported python and ignoring 403 lint errors. What do you think @mrlesmithjr?

**Comment by mrlesmithjr** [comment]
I agree. No sense in supporting legacy.

**Comment by elcomtik** [comment]
I fixed test errors, it's ready to merge

**Comment by mrlesmithjr** [comment]
@elcomtik @nertwork - Merged!

**Comment by elcomtik** [comment]
Thanks

**Pull request merged**
