### PR TITLE
Added support for BFD daemon configuration for BGP routing protocol

### PR DESCRIPTION
**Pull request by elcomtik**
Resolves issue https://github.com/mrlesmithjr/ansible-frr/issues/53

### CODE REVIEW

**Comment by elcomtik** [comment]
@mrlesmithjr can you please review this and eventually merge it?

**Comment by elcomtik** [comment]
@mrlesmithjr Do you have some time to look at this? There should not be any backward-incompatible changes.

**Review by nertwork — APPROVED** [review]
Looks good - thank you!

**Comment by elcomtik** [comment]
Thaks

**Pull request merged**
